theme: jekyll-theme-cayman
title: Technical Literacy
description: |
  Living in the technical world
author: Tim Kellogg

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  math_engine: katex

github:
  is_project_page: false

